name: Update RSS

on:
  pull_request:
  push:
    branches:
    - main
  schedule:
    - cron: "0 8 * * *"

jobs:
  update_rss_feeds:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install
    - name: Run pyhumble
      run: poetry run pyhumble
    - uses: stefanzweifel/git-auto-commit-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
      with:
        commit_message: Update RSS feeds using GitHub Workflow
        branch: main
